# Generated by Django 5.2 on 2025-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChloeStore', '0002_category_rename_created_at_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('store manager', 'Store manager'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
