# Generated by Django 5.2.5 on 2025-08-31 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChloeStore', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
