# Generated by Django 5.2.5 on 2025-08-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChloeStore', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
