databases:
  - name: chloestoredb
    plan: free
    databaseName: chloestoredb
    user: smartco

services:
  - type: web
    plan: free
    name: ECommerceApi
    runtime: python3
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn ECommerceApi.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chloestoredb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4